### ISSUE TITLE
Administration Cluster Authentication

### ISSUE THREAD

**Issue by werzl** [filetrust/icap-management-ui#161]
@gw-sbirch @MattCavey 

## Description
At the moment we're storing a JWT in client storage. Possibly open to XSS attacks, think it might be best to review how we're using tokens to authenticate requests between services in the administration cluster.

## Proposal
Use cookies and session storage to store the JWT (with the user's account details, as well as any scopes if we decide to add them).

## Tasks
- [ ] Setup Redis in the management UI service
- [ ] Create session middleware https://www.npmjs.com/package/express-session
- [ ] Store JWT returned from the identity-management-api in session/redis cache
- [ ] Retrieve JWT from session/redis storage and use it as bearer token
- [ ] Update transaction-query-aggregator and policy-management-api to accept bearer tokens
